"""Upgrade real, independently authored legacy SQLite files without rewriting evidence."""
import concurrent.futures
import os
import sqlite3
import subprocess
import sys
import threading
from pathlib import Path

import pytest
from pydantic import ValidationError
from typer.testing import CliRunner

from core.domain.types import Event, EventType, Investigation, Session
from core.security.models import SecurityAudit, SecurityFinding, SecuritySolution
from infrastructure.database import migrations
from infrastructure.database.repository import Database
from infrastructure.database.storage import StorageError
from surfaces.entrypoint import app


# A separate legacy fixture, not generated by the production migration runner.
LEGACY_SQL = '''
CREATE TABLE sessions (
    id TEXT PRIMARY KEY, repository_path TEXT NOT NULL, starting_commit TEXT NOT NULL,
    branch TEXT NOT NULL, started_at TEXT NOT NULL, ended_at TEXT
);
CREATE TABLE events (
    id INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT NOT NULL,
    timestamp TEXT NOT NULL, event_type TEXT NOT NULL, payload TEXT NOT NULL
);
CREATE INDEX events_session ON events(session_id, id);
CREATE TABLE security_audits (id TEXT PRIMARY KEY, started_at TEXT NOT NULL, payload TEXT NOT NULL);
CREATE TABLE security_solutions (id TEXT PRIMARY KEY, started_at TEXT NOT NULL, payload TEXT NOT NULL);
CREATE TABLE investigations (id TEXT PRIMARY KEY, session_id TEXT NOT NULL, payload TEXT NOT NULL);
CREATE INDEX investigations_session_started ON investigations (
    session_id, json_extract(payload, '$.started_at') DESC, id DESC
);
'''


@pytest.fixture
def legacy(tmp_path):
    folder = tmp_path / '.ghost'
    folder.mkdir(mode=0o700)
    path = folder / 'ghost.db'
    with sqlite3.connect(path) as db:
        db.executescript(LEGACY_SQL)
        session = Session(id='legacy-session', repository_path=str(tmp_path), starting_commit='abc', branch='main')
        event = Event(session_id=session.id, event_type=EventType.COMMAND_FINISHED, command='pytest -q', exit_code=1)
        investigation = Investigation(id='legacy-investigation', session_id=session.id, status='failed',
                                      notes=['Interrupted legacy run; no repair verified.'])
        finding = SecurityFinding(id='legacy-finding', rule='B307', title='Expression evaluation', path='parser.py',
                                  line=2, severity='HIGH', confidence='MEDIUM', file_sha256='a' * 64)
        audit = SecurityAudit(id='legacy-audit', status='incomplete', findings=[finding],
                              files={'parser.py': 'a' * 64}, notes=['Incomplete evidence stays incomplete.'])
        solution = SecuritySolution(id='legacy-solution', audit_id=audit.id, finding_id=finding.id,
                                    status='blocked', notes=['Unsupported verification.'])
        db.execute('INSERT INTO sessions VALUES (?, ?, ?, ?, ?, ?)',
                   (session.id, session.repository_path, session.starting_commit, session.branch,
                    session.started_at, session.ended_at))
        db.execute('INSERT INTO events VALUES (?, ?, ?, ?, ?)',
                   (42, event.session_id, event.timestamp, event.event_type.value, event.model_dump_json()))
        db.execute('INSERT INTO investigations VALUES (?, ?, ?)',
                   (investigation.id, investigation.session_id, investigation.model_dump_json()))
        for table, record in [('security_audits', audit), ('security_solutions', solution)]:
            db.execute(f'INSERT INTO {table} VALUES (?, ?, ?)', (record.id, record.started_at, record.model_dump_json()))
    path.chmod(0o600)
    return tmp_path, path, (session, event, investigation, audit, solution)


def snapshot(path):
    with sqlite3.connect(path) as db:
        tables = db.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").fetchall()
        return {
            'version': db.execute('PRAGMA user_version').fetchone()[0],
            'schema': db.execute('SELECT type, name, tbl_name, sql FROM sqlite_master ORDER BY name').fetchall(),
            'rows': {name: db.execute(f'SELECT * FROM "{name}"').fetchall() for (name,) in tables},
        }


def test_legacy_upgrade_preserves_every_row_payload_and_evidence_state(legacy):
    repo, path, (session, event, investigation, audit, solution) = legacy
    before = snapshot(path)
    db = Database(repo)
    after = snapshot(path)
    assert after == {**before, 'version': 1}
    assert db.latest_session() == session
    assert db.events(session.id) == [event]
    assert db.latest_investigation(session.id) == investigation
    assert db.latest_audit() == audit
    assert db.latest_solution() == solution
    db.add_event(event)
    with db.connect(write=False) as connection:
        assert connection.execute('SELECT max(id) FROM events').fetchone()[0] == 43
    assert Database(repo).resolve_audit(audit.id).status == 'incomplete'


def test_empty_and_partial_legacy_databases_initialize_and_repeat_safely(tmp_path):
    folder = tmp_path / '.ghost'
    folder.mkdir()
    path = folder / 'ghost.db'
    with sqlite3.connect(path) as db:
        db.execute('''CREATE TABLE sessions (
            id TEXT PRIMARY KEY, repository_path TEXT NOT NULL, starting_commit TEXT NOT NULL,
            branch TEXT NOT NULL, started_at TEXT NOT NULL, ended_at TEXT
        )''')
        db.execute('INSERT INTO sessions VALUES (?, ?, ?, ?, ?, ?)',
                   ('partial-session', str(tmp_path), 'abc', 'main', '2026-10-01', None))
    assert Database(tmp_path).latest_session().id == 'partial-session'
    before = snapshot(path)
    Database(tmp_path)
    assert snapshot(path) == before
    fresh = Database(tmp_path / 'fresh')
    assert snapshot(fresh.path)['version'] == 1


@pytest.mark.parametrize('version', [2, 999, -1])
def test_unknown_versions_are_rejected_without_changing_database_or_journal_mode(legacy, version):
    repo, path, _ = legacy
    with sqlite3.connect(path) as db:
        db.execute(f'PRAGMA user_version={version}')
    before = path.read_bytes()
    with pytest.raises(migrations.DatabaseCompatibilityError, match='Upgrade Ghost'):
        Database(repo)
    assert path.read_bytes() == before
    assert not path.with_name('ghost.db-wal').exists()


@pytest.mark.parametrize('version', [0, 2])
def test_existing_database_handles_refuse_reads_and_writes_after_version_change(tmp_path, version):
    db = Database(tmp_path)
    session = Session(repository_path=str(tmp_path), starting_commit='abc', branch='main')
    with sqlite3.connect(db.path) as connection:
        connection.execute(f'PRAGMA user_version={version}')
    before = snapshot(db.path)
    with pytest.raises(migrations.DatabaseCompatibilityError):
        db.start(session)
    with pytest.raises(migrations.DatabaseCompatibilityError):
        db.latest_session()
    assert snapshot(db.path) == before


@pytest.mark.parametrize('failure', [RuntimeError, KeyboardInterrupt])
def test_exception_rolls_back_schema_payload_changes_and_version(legacy, monkeypatch, failure):
    repo, path, _ = legacy
    before = snapshot(path)
    def interrupted(connection):
        connection.execute('CREATE TABLE unfinished (id TEXT)')
        connection.execute('DELETE FROM security_audits')
        connection.execute('PRAGMA user_version=1')
        raise failure('synthetic migration interruption')
    monkeypatch.setattr(migrations, 'MIGRATIONS', (interrupted,))
    with pytest.raises(failure):
        Database(repo)
    assert snapshot(path) == before
    monkeypatch.undo()
    assert Database(repo).latest_audit().id == 'legacy-audit'


@pytest.mark.parametrize('fail_second', [False, True])
def test_ordered_upgrades_commit_together_or_roll_back_together(legacy, monkeypatch, fail_second):
    repo, path, _ = legacy
    before = snapshot(path)
    steps = []
    first = migrations.MIGRATIONS[0]
    def step_one(connection):
        steps.append(connection.execute('PRAGMA user_version').fetchone()[0])
        first(connection)
    def step_two(connection):
        steps.append(connection.execute('PRAGMA user_version').fetchone()[0])
        connection.execute('CREATE TABLE future_metadata (name TEXT PRIMARY KEY)')
        connection.execute("UPDATE sessions SET ended_at='2026-10-09'")
        if fail_second:
            raise RuntimeError('synthetic second migration failure')
    monkeypatch.setattr(migrations, 'SCHEMA_VERSION', 2)
    monkeypatch.setitem(migrations.SCHEMAS, 2, (
        {**migrations.TABLES, 'future_metadata': (('name', 'TEXT', 0, 1),)}, migrations.INDEXES,
    ))
    monkeypatch.setattr(migrations, 'MIGRATIONS', (step_one, step_two))
    if fail_second:
        with pytest.raises(RuntimeError):
            Database(repo)
        assert snapshot(path) == before
    else:
        db = Database(repo)
        assert snapshot(path)['version'] == 2
        assert db.latest_session().ended_at == '2026-10-09'
        Database(repo)
        with sqlite3.connect(path) as connection:
            connection.execute('DROP TABLE future_metadata')
            connection.execute('PRAGMA user_version=1')
        Database(repo)  # A version 1 database upgrades using its historical layout.
        assert snapshot(path)['version'] == 2
        assert steps == [0, 1, 1]
        return
    assert steps == [0, 1]


def test_abrupt_process_exit_recovers_uncommitted_migration(legacy):
    repo, path, _ = legacy
    before = snapshot(path)
    script = '''
import os
import sys
from pathlib import Path
from infrastructure.database import migrations
from infrastructure.database.repository import Database
def crash(db):
    db.execute('CREATE TABLE unfinished (id TEXT)')
    db.execute('DELETE FROM security_audits')
    db.execute('PRAGMA user_version=1')
    os._exit(23)
migrations.MIGRATIONS = (crash,)
Database(Path(sys.argv[1]))
'''
    result = subprocess.run([sys.executable, '-c', script, str(repo)],
                            cwd=Path(__file__).resolve().parents[1], capture_output=True, timeout=15)
    assert result.returncode == 23, result.stderr
    assert snapshot(path) == before
    assert Database(repo).latest_audit().id == 'legacy-audit'


def test_simultaneous_legacy_startup_migrates_once_and_retains_all_writes(legacy, monkeypatch):
    repo, path, _ = legacy
    calls = []
    original = migrations.MIGRATIONS[0]
    def counted(connection):
        calls.append(1)
        original(connection)
    monkeypatch.setattr(migrations, 'MIGRATIONS', (counted,))
    barrier = threading.Barrier(6, timeout=10)
    def start(number):
        barrier.wait()
        db = Database(repo)
        db.start(Session(id=f'new-{number}', repository_path=str(repo), starting_commit='abc', branch='main'))
    with concurrent.futures.ThreadPoolExecutor(max_workers=6) as workers:
        list(workers.map(start, range(6)))
    assert calls == [1]
    assert len(Database(repo).sessions()) == 7
    assert snapshot(path)['version'] == 1


@pytest.mark.parametrize('sql', [
    'CREATE TABLE foreign_data (value TEXT)',
    'CREATE TABLE sqlitex_hidden (value TEXT)',
    'ALTER TABLE sessions ADD COLUMN unsupported TEXT',
    'CREATE VIEW foreign_view AS SELECT * FROM sessions',
    'CREATE TRIGGER foreign_trigger AFTER DELETE ON sessions BEGIN DELETE FROM events; END',
    'DROP TABLE security_audits',
    'DROP INDEX events_session',
])
def test_unrecognized_or_incomplete_versioned_schema_is_preserved(legacy, sql):
    repo, path, _ = legacy
    with sqlite3.connect(path) as db:
        db.execute(sql)
        db.execute('PRAGMA user_version=1')
    before = path.read_bytes()
    with pytest.raises(migrations.DatabaseCompatibilityError, match='Back up .ghost'):
        Database(repo)
    assert path.read_bytes() == before


def test_bad_index_payload_leaves_partial_legacy_schema_unversioned(legacy):
    repo, path, _ = legacy
    with sqlite3.connect(path) as db:
        db.execute('DROP INDEX investigations_session_started')
        db.execute("UPDATE investigations SET payload='not json'")
        db.execute('DROP TABLE security_solutions')
    before = snapshot(path)
    with pytest.raises(sqlite3.DatabaseError):
        Database(repo)
    assert snapshot(path) == before


def test_structural_upgrade_preserves_invalid_payloads_for_explicit_reader_validation(legacy):
    repo, path, _ = legacy
    with sqlite3.connect(path) as db:
        db.execute("UPDATE security_audits SET payload='not json'")
    before = snapshot(path)
    db = Database(repo)
    assert snapshot(path) == {**before, 'version': 1}
    with pytest.raises(ValidationError):
        db.latest_audit()


def test_failed_storage_access_never_stamps_a_version(legacy, monkeypatch):
    repo, path, _ = legacy
    before = path.read_bytes()
    import infrastructure.database.storage as storage_module
    original = storage_module.os.open
    def deny(name, *args, **kwargs):
        if name == 'ghost.db':
            raise PermissionError('synthetic denied storage read')
        return original(name, *args, **kwargs)
    monkeypatch.setattr(storage_module.os, 'open', deny)
    with pytest.raises(StorageError):
        Database(repo)
    assert path.read_bytes() == before


@pytest.mark.skipif(os.geteuid() == 0, reason='Root bypasses POSIX file permission checks')
def test_read_only_database_preserves_bytes_and_version(legacy):
    repo, path, _ = legacy
    before = path.read_bytes()
    path.chmod(0o400)
    try:
        with pytest.raises(StorageError):
            Database(repo)
        assert path.read_bytes() == before
    finally:
        path.chmod(0o600)


def test_future_database_cli_error_is_actionable_and_never_leaks_payloads(legacy, monkeypatch):
    repo, path, _ = legacy
    subprocess.run(['git', 'init', '-q', '--template=', str(repo)], check=True)
    subprocess.run(['git', '-C', str(repo), '-c', 'user.name=Test', '-c', 'user.email=test@example.invalid',
                    '-c', 'commit.gpgsign=false', 'commit', '--allow-empty', '-qm', 'initial'], check=True)
    with sqlite3.connect(path) as db:
        db.execute('PRAGMA user_version=99')
        db.execute("UPDATE security_audits SET payload='synthetic-private-payload'")
    before = path.read_bytes()
    monkeypatch.chdir(repo)
    response = CliRunner().invoke(app, ['status'])
    assert response.exit_code == 2
    assert 'Upgrade Ghost' in response.output and 'Traceback' not in response.output
    assert 'synthetic-private' not in response.output
    assert path.read_bytes() == before


def test_read_snapshot_remains_consistent_while_another_connection_writes(tmp_path):
    db = Database(tmp_path)
    session = Session(repository_path=str(tmp_path), starting_commit='abc', branch='main')
    with db.connect(write=False) as reader:
        assert reader.execute('SELECT count(*) FROM sessions').fetchone()[0] == 0
        db.start(session)
        assert reader.execute('SELECT count(*) FROM sessions').fetchone()[0] == 0
    assert db.latest_session() == session


def test_history_connection_cannot_accidentally_write(tmp_path):
    db = Database(tmp_path)
    with db.connect(write=False) as connection:
        with pytest.raises(sqlite3.OperationalError, match='readonly'):
            connection.execute('DELETE FROM sessions')
